apiVersion: v1
kind: ConfigMap
metadata:
  name: yaam-config
  namespace: {{ .Values.namespace }}
data:
  yaam2.conf: |    
    port: 25213
    user: hello
    pass: world
    cachedir: "/d01/cache/"
    caches:
      apt:
        debian9:
          url: http://mirror.mephi.ru/debian/
      maven:
        3rdparty-maven:
          url: https://repo.maven.apache.org/maven2/
        rgv:
          url: https://plugins.gradle.org/m2/
        maven-spring:
          url: https://repo.spring.io/release/
        nexus:
          url: https://some-nexus/repository/some-repo/
          user: some-user
          pass: some-pass
      npm:
        npmjs:
          url: https://registry.npmjs.org/
          